# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/GICM_Xilinx_Tutorial/Tutorial_00/Led_Vivado_Prj/Led_Vivado_Prj.srcs/sources_1/bd/design_Led_Ctrl/ip/design_Led_Ctrl_processing_system7_0_0/design_Led_Ctrl_processing_system7_0_0.xci
# IP: The module: 'design_Led_Ctrl_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/GICM_Xilinx_Tutorial/Tutorial_00/Led_Vivado_Prj/Led_Vivado_Prj.gen/sources_1/bd/design_Led_Ctrl/ip/design_Led_Ctrl_processing_system7_0_0/design_Led_Ctrl_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Led_Ctrl_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitHub/GICM_Xilinx_Tutorial/Tutorial_00/Led_Vivado_Prj/Led_Vivado_Prj.srcs/sources_1/bd/design_Led_Ctrl/ip/design_Led_Ctrl_processing_system7_0_0/design_Led_Ctrl_processing_system7_0_0.xci
# IP: The module: 'design_Led_Ctrl_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/GICM_Xilinx_Tutorial/Tutorial_00/Led_Vivado_Prj/Led_Vivado_Prj.gen/sources_1/bd/design_Led_Ctrl/ip/design_Led_Ctrl_processing_system7_0_0/design_Led_Ctrl_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Led_Ctrl_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
