# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z1.xdc

# Block Designs: bd/design_Led_Ctrl/design_Led_Ctrl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl || ORIG_REF_NAME==design_Led_Ctrl} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_myip_axi_leds_ctrl_0_0/design_Led_Ctrl_myip_axi_leds_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_myip_axi_leds_ctrl_0_0 || ORIG_REF_NAME==design_Led_Ctrl_myip_axi_leds_ctrl_0_0} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_processing_system7_0_0/design_Led_Ctrl_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_processing_system7_0_0 || ORIG_REF_NAME==design_Led_Ctrl_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_ps7_0_axi_periph_0/design_Led_Ctrl_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_Led_Ctrl_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_rst_ps7_0_100M_0/design_Led_Ctrl_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_Led_Ctrl_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_leds_ctrl_0_0/design_Led_Ctrl_leds_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_leds_ctrl_0_0 || ORIG_REF_NAME==design_Led_Ctrl_leds_ctrl_0_0} -quiet] -quiet

# IP: bd/design_Led_Ctrl/ip/design_Led_Ctrl_auto_pc_0/design_Led_Ctrl_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_Led_Ctrl_auto_pc_0 || ORIG_REF_NAME==design_Led_Ctrl_auto_pc_0} -quiet] -quiet

# XDC: c:/GitHub/GICM_Xilinx_Tutorial/Tutorial_00/Led_Vivado_Prj/Led_Vivado_Prj.gen/sources_1/bd/design_Led_Ctrl/design_Led_Ctrl_ooc.xdc
